DROP TABLE attributes;
DELETE FROM images;

CREATE TABLE attribute_groups (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name TEXT SECONDERY KEY UNIQUE NOT NULL
);

CREATE TABLE attributes (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name TEXT SECONDARY KEY UNIQUE NOT NULL,
    group_id INTEGER
);